import dynamic from 'next/dynamic'
import { Suspense } from 'react'

import './globals.css'
import "react-toastify/dist/ReactToastify.css"


import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer'

const StoreProvider = dynamic(() => import("@/redux/Povider"), { ssr: false });
import ToastProvider from '@/components/utils/ToastProvider';

export const metadata = {
  title: 'BoomCheck',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="font-sans">
        <StoreProvider>
          <ToastProvider>
            <Navbar />
            <main>
              {children}
            </main>

            <Suspense fallback={<p className='text-center italic text-gray-400'>Loading...</p>}>
              <Footer />
            </Suspense>
          </ToastProvider>
        </StoreProvider>
      </body>
    </html>
  )
}
